#!/usr/bin/python

import sys
import socket
import dns.resolver

host = sys.argv[1]

mx = []
try:
    mx = dns.resolver.resolve(sys.argv[1], 'MX')
except dns.resolver.NoAnswer:
    sys.exit(0)


for m in mx:
    mhost = str(m.exchange).rstrip('.')

    if mhost == "":
        # "Null MX" record / RFC 7505
        continue

    try:
        socket.inet_aton(mhost)
        print("%s has IPv4 MX record %s" % (host, mhost))
        continue
    except Exception:
        pass
    try:
        socket.inet_pton(socket.AF_INET6, mhost)
        print("%s has IPv6 MX record %s" % (host, mhost))
        continue
    except Exception:
        pass
